# Generated by Django 4.1.13 on 2024-05-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                # ('last_login', models.DateTimeField(
                #     blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                # ('age', models.IntegerField()),
                # ('phone_number', models.CharField(max_length=10)),
                # ('is_active', models.BooleanField(default=True)),
                # ('is_doctor', models.BooleanField(default=False)),
                # ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
